// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenMart.Data;

namespace PenMart.Migrations
{
    [DbContext(typeof(PenMartContext))]
    [Migration("20251014114732_UpdateProductImageUrls3")]
    partial class UpdateProductImageUrls3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PenMart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "نوشت افزار",
                            Discription = "انواع و اقسام خودکار ها و مداد ها در رنگ ها و مدل های مختلف"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "دفتر و کاغذ",
                            Discription = "انواع و اقسام دفتر و کاغذ در اندازه های مختلف"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "لوازم نقاشی و هنری",
                            Discription = "انواع و اقسام رنگ، قلم‌مو، گواش و..."
                        });
                });

            modelBuilder.Entity("PenMart.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 5000m,
                            QuantityInStock = 10
                        },
                        new
                        {
                            Id = 2,
                            Price = 7000m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 3,
                            Price = 6500m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            Id = 4,
                            Price = 140000m,
                            QuantityInStock = 35
                        },
                        new
                        {
                            Id = 5,
                            Price = 65000m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = 6,
                            Price = 80000m,
                            QuantityInStock = 17
                        },
                        new
                        {
                            Id = 7,
                            Price = 450000m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 8,
                            Price = 330000m,
                            QuantityInStock = 22
                        },
                        new
                        {
                            Id = 9,
                            Price = 664000m,
                            QuantityInStock = 13
                        });
                });

            modelBuilder.Entity("PenMart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Discription = "خودکار کلاسیک و پرکاربرد",
                            ItemId = 1,
                            Name = "خودکار بیک آبی"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Discription = "مداد طراحی با کیفیت بالا",
                            ItemId = 2,
                            Name = "مداد ۲B فابر کاستل"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Discription = "مناسب برای طراحی و نقاشی",
                            ItemId = 3,
                            Name = "مداد رنگی استدلر ۱۲ رنگ"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Discription = "دفتر سیمی مناسب برای یادداشت روزانه و مدرسه",
                            ItemId = 4,
                            Name = "دفتر ۱۰۰ برگ سیمی"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Discription = "دفترچه جیبی برای یادداشت سریع",
                            ItemId = 5,
                            Name = "دفترچه یادداشت کوچک"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Discription = "دفتر مخصوص یادگیری و تمرین زبان",
                            ItemId = 6,
                            Name = "دفتر زبان ۷۰ برگ"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Discription = "مناسب برای نقاشی و کارهای هنری کودک و بزرگسال",
                            ItemId = 7,
                            Name = "گواش ۱۲ رنگ فابر کاستل"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Discription = "رنگ‌های با کیفیت و شفاف برای طراحی و نقاشی",
                            ItemId = 8,
                            Name = "آبرنگ ۱۲ رنگ استدلر"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Discription = "برای ترکیب رنگ‌ها و نقاشی راحت‌تر",
                            ItemId = 9,
                            Name = "پالت رنگ پلاستیکی"
                        });
                });

            modelBuilder.Entity("PenMart.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            ProductId = 1,
                            Url = "/Images/bic1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            ProductId = 1,
                            Url = "/Images/bic2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = false,
                            ProductId = 1,
                            Url = "/Images/bic3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = true,
                            ProductId = 2,
                            Url = "/Images/faber1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = false,
                            ProductId = 2,
                            Url = "/Images/faber2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            ProductId = 2,
                            Url = "/Images/faber3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsMain = true,
                            ProductId = 3,
                            Url = "/Images/ravannevis1.png"
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            ProductId = 3,
                            Url = "/Images/ravannevis2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsMain = false,
                            ProductId = 3,
                            Url = "/Images/ravannevis3.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsMain = true,
                            ProductId = 4,
                            Url = "/Images/daftar1.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsMain = false,
                            ProductId = 4,
                            Url = "/Images/daftar2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsMain = false,
                            ProductId = 4,
                            Url = "/Images/daftar3.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            ProductId = 5,
                            Url = "/Images/daftarche1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsMain = false,
                            ProductId = 5,
                            Url = "/Images/daftarche2.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsMain = false,
                            ProductId = 5,
                            Url = "/Images/daftarche3.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsMain = true,
                            ProductId = 6,
                            Url = "/Images/daftarzaban1.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsMain = false,
                            ProductId = 6,
                            Url = "/Images/daftarzaban2.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsMain = false,
                            ProductId = 6,
                            Url = "/Images/daftarzaban3.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsMain = true,
                            ProductId = 7,
                            Url = "/Images/guash1.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsMain = false,
                            ProductId = 7,
                            Url = "/Images/guash2.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsMain = false,
                            ProductId = 7,
                            Url = "/Images/guash3.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsMain = true,
                            ProductId = 8,
                            Url = "/Images/abrang1.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsMain = false,
                            ProductId = 8,
                            Url = "/Images/abrang2.jpg"
                        },
                        new
                        {
                            Id = 24,
                            IsMain = false,
                            ProductId = 8,
                            Url = "/Images/abrang3.jpg"
                        },
                        new
                        {
                            Id = 25,
                            IsMain = true,
                            ProductId = 9,
                            Url = "/Images/palet1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            IsMain = false,
                            ProductId = 9,
                            Url = "/Images/palet2.jpg"
                        },
                        new
                        {
                            Id = 27,
                            IsMain = false,
                            ProductId = 9,
                            Url = "/Images/palet3.jpg"
                        });
                });

            modelBuilder.Entity("PenMart.Models.Product", b =>
                {
                    b.HasOne("PenMart.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenMart.Models.Item", "Item")
                        .WithOne("Product")
                        .HasForeignKey("PenMart.Models.Product", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PenMart.Models.ProductImage", b =>
                {
                    b.HasOne("PenMart.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
