// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenMart.Data;

#nullable disable

namespace PenMart.Migrations
{
    [DbContext(typeof(PenMartContext))]
    [Migration("20260615123954_FixImageUrls")]
    partial class FixImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PenMart.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PenMart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "نوشت افزار",
                            Discription = "انواع و اقسام خودکار ها و مداد ها در رنگ ها و مدل های مختلف",
                            Url = "/Images/Categoreis/pens5.PNG"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "دفتر و کاغذ",
                            Discription = "انواع و اقسام دفتر و کاغذ در اندازه های مختلف",
                            Url = "/Images/Categoreis/papers.PNG"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "لوازم نقاشی و هنری",
                            Discription = "انواع و اقسام رنگ، قلم‌مو، گواش و...",
                            Url = "/Images/Categoreis/naghashi.PNG"
                        });
                });

            modelBuilder.Entity("PenMart.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 5000m,
                            QuantityInStock = 10
                        },
                        new
                        {
                            Id = 2,
                            Price = 7000m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 3,
                            Price = 6500m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            Id = 4,
                            Price = 140000m,
                            QuantityInStock = 35
                        },
                        new
                        {
                            Id = 5,
                            Price = 65000m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = 6,
                            Price = 80000m,
                            QuantityInStock = 17
                        },
                        new
                        {
                            Id = 7,
                            Price = 450000m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 8,
                            Price = 330000m,
                            QuantityInStock = 22
                        },
                        new
                        {
                            Id = 9,
                            Price = 664000m,
                            QuantityInStock = 13
                        });
                });

            modelBuilder.Entity("PenMart.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinaly")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PenMart.Models.OrderDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PenMart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Discription = "خودکار کلاسیک و پرکاربرد",
                            ItemId = 1,
                            Name = "خودکار بیک آبی"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Discription = "مداد طراحی با کیفیت بالا",
                            ItemId = 2,
                            Name = "مداد ۲B فابر کاستل"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Discription = "مناسب برای طراحی و نقاشی",
                            ItemId = 3,
                            Name = "مداد رنگی استدلر ۱۲ رنگ"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Discription = "دفتر سیمی مناسب برای یادداشت روزانه و مدرسه",
                            ItemId = 4,
                            Name = "دفتر ۱۰۰ برگ سیمی"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Discription = "دفترچه جیبی برای یادداشت سریع",
                            ItemId = 5,
                            Name = "دفترچه یادداشت کوچک"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Discription = "دفتر مخصوص یادگیری و تمرین زبان",
                            ItemId = 6,
                            Name = "دفتر زبان ۷۰ برگ"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Discription = "مناسب برای نقاشی و کارهای هنری کودک و بزرگسال",
                            ItemId = 7,
                            Name = "گواش ۱۲ رنگ فابر کاستل"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Discription = "رنگ‌های با کیفیت و شفاف برای طراحی و نقاشی",
                            ItemId = 8,
                            Name = "آبرنگ ۱۲ رنگ استدلر"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Discription = "برای ترکیب رنگ‌ها و نقاشی راحت‌تر",
                            ItemId = 9,
                            Name = "پالت رنگ پلاستیکی"
                        });
                });

            modelBuilder.Entity("PenMart.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            ProductId = 1,
                            Url = "/Images/Products/bic1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            ProductId = 1,
                            Url = "/Images/Products/bic2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = false,
                            ProductId = 1,
                            Url = "/Images/Products/bic3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = true,
                            ProductId = 2,
                            Url = "/Images/Products/faber1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = false,
                            ProductId = 2,
                            Url = "/Images/Products/faber2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            ProductId = 2,
                            Url = "/Images/Products/faber3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsMain = true,
                            ProductId = 3,
                            Url = "/Images/Products/ravannevis1.png"
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            ProductId = 3,
                            Url = "/Images/Products/ravannevis2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsMain = false,
                            ProductId = 3,
                            Url = "/Images/Products/ravannevis3.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsMain = true,
                            ProductId = 4,
                            Url = "/Images/Products/daftar1.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsMain = false,
                            ProductId = 4,
                            Url = "/Images/Products/daftar2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsMain = false,
                            ProductId = 4,
                            Url = "/Images/Products/daftar3.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            ProductId = 5,
                            Url = "/Images/Products/daftarche1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsMain = false,
                            ProductId = 5,
                            Url = "/Images/Products/daftarche2.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsMain = false,
                            ProductId = 5,
                            Url = "/Images/Products/daftarche3.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsMain = true,
                            ProductId = 6,
                            Url = "/Images/Products/daftarzaban1.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsMain = false,
                            ProductId = 6,
                            Url = "/Images/Products/daftarzaban2.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsMain = false,
                            ProductId = 6,
                            Url = "/Images/Products/daftarzaban3.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsMain = true,
                            ProductId = 7,
                            Url = "/Images/Products/guash1.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsMain = false,
                            ProductId = 7,
                            Url = "/Images/Products/guash2.jpg"
                        },
                        new
                        {
                            Id = 21,
                            IsMain = false,
                            ProductId = 7,
                            Url = "/Images/Products/guash3.jpg"
                        },
                        new
                        {
                            Id = 22,
                            IsMain = true,
                            ProductId = 8,
                            Url = "/Images/Products/abrang1.jpg"
                        },
                        new
                        {
                            Id = 23,
                            IsMain = false,
                            ProductId = 8,
                            Url = "/Images/Products/abrang2.jpg"
                        },
                        new
                        {
                            Id = 24,
                            IsMain = false,
                            ProductId = 8,
                            Url = "/Images/Products/abrang3.jpg"
                        },
                        new
                        {
                            Id = 25,
                            IsMain = true,
                            ProductId = 9,
                            Url = "/Images/Products/palet1.jpg"
                        },
                        new
                        {
                            Id = 26,
                            IsMain = false,
                            ProductId = 9,
                            Url = "/Images/Products/palet2.jpg"
                        },
                        new
                        {
                            Id = 27,
                            IsMain = false,
                            ProductId = 9,
                            Url = "/Images/Products/palet3.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PenMart.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PenMart.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenMart.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PenMart.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PenMart.Models.Order", b =>
                {
                    b.HasOne("PenMart.Models.ApplicationUser", "User")
                        .WithMany("orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PenMart.Models.OrderDetail", b =>
                {
                    b.HasOne("PenMart.Models.Order", "order")
                        .WithMany("orderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenMart.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("PenMart.Models.Product", b =>
                {
                    b.HasOne("PenMart.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenMart.Models.Item", "Item")
                        .WithOne("Product")
                        .HasForeignKey("PenMart.Models.Product", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PenMart.Models.ProductImage", b =>
                {
                    b.HasOne("PenMart.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PenMart.Models.ApplicationUser", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("PenMart.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PenMart.Models.Item", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("PenMart.Models.Order", b =>
                {
                    b.Navigation("orderDetails");
                });

            modelBuilder.Entity("PenMart.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
